### ISSUE TITLE
Support placement chess variant (Bronstein/Benko/Pre-chess)

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#10]
It's implemented in pychess, cutechess and ddugovic variant stockfish under variant name "placement".

The rules: http://www.quantumgambitz.com/blog/chess/cga/bronstein-chess-pre-chess-shuffle-chess

https://github.com/ddugovic/Stockfish/tree/placement
https://github.com/cutechess/cutechess/pull/421

**Comment by ianfab** [comment]
Thanks for the suggestion. Placement chess would actually be a nice preparation step for a future Sittuyin implementation, since both feature the setup-phase (or mandatory piece drops) and piece drops behind pawns.

**Comment by ianfab** [comment]
A first implementation is available on branch [placement](https://github.com/ianfab/Fairy-Stockfish/tree/placement). The castling rights are so far not set when the kings/rooks are dropped, but apart from that the rules should be implemented, at least the perft results for the starting position are looking good (they would theoretically be wrong starting from 21 ply due to the missing castling rights). I have not done much further testing yet though.

**Comment by ianfab** [comment]
Setting the castling rights turned out to be much less complicated than expected. The implementation of placement chess should be complete now. I will test it tomorrow and hopefully can merge it then.

**Comment by gbtami** [comment]
Thx a lot! I'm looking forward to see Sittuyin being implemented now ;)

**Comment by ianfab** [comment]
Me too ;).

I noticed that it was not compatible yet with the lichess/pychess-style FENs for drop games. After fixing that, the placement chess implementation works nicely now with pychess.

**Comment by gbtami** [comment]
I'v just noticed it today also :) Today I fixed a setup phase bug, and now started to work on promotions problems also.

**Comment by ianfab** [comment]
Ok, thanks.
