### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by grandmastermac** [ianfab/Fairy-Stockfish#109]
Hey,
I'm looking to use fairy stockfish js in a frontend react application, closed source.
Am I'm allowed to do so?

Main thing of concern is the GPLv3 license infects the parent source that links to it, whether via a <script/> tag or requires() compile.

Is there any way to use this engine on the frontend without needing to release the entire source? I am more than happy to release the source of the engine mods themselves.

Thanks.

**Comment by ianfab** [comment]
Hi, I can not give you legal advice, but I also assume that the copyleft would apply to your frontend application as well. Since I am bound to GPL by the upstream copyleft from Stockfish, there is also no way that I could provide Fairy-Stockfish (js) with a different license that would allow you to not be bound to the copyleft.

I am curious about the modifications to Fairy-Stockfish. Are you talking about the WASM fork or did you modify it to a pure JS version? Or did you also do modifications to the engine core that might be useful to merge here? And since I am quite interested in chess variants I am also curious about your application. Can you say more about it?

**Comment by grandmastermac** [comment]
Hey Ian, thanks for you prompt reply. We haven't created the engine or modified any engine yet. But we are looking to. We just wanted to make sure we do the right thing from a licensing perspective. We are more than happy to merge in our mods into the engine core so the variant can be offered to everybody. But we would prefer to keep the SuperChess web application private as it will contain a lot of intellectual property around gaming.

The chess variant is called SuperChess and modifies three of the pieces. Two you will already be familiar with, the Chancellor and the Arch-bishop. The third, the Wildebeest may be new to you. You can see the full rules here https://www.chesspower.co.nz/superchess.

I hope you can help with some useful suggestions.

**Comment by grandmastermac** [comment]
Any thoughts Ian?

**Comment by ianfab** [comment]
On what specifically? Regarding SuperChess itself, I think that the variant is a bit overcrowded with strong pieces, which might take away some strategical aspects, making it focused mainly on calculation. Regarding the licensing I think there is no solution to integrate Fairy-Stockfish into a closed source software without violating the license, which is on purpose by the choice of GPL.

**Comment by grandmastermac** [comment]
Hi Ian, sorry - I meant licensing. Thanks for the feedback. And also, thank you for your comments on your reflections on SuperChess.
