### ISSUE TITLE
Code Error compiling with VS2015

### ISSUE THREAD

**Issue by defrag1971** [ianfab/Fairy-Stockfish#111]
In **xboard.cpp**:
sync_cout << "feature setboard=1 usermove=1 time=1 memory=1 smp=1 colors=0 draw=0 name=0 sigint=0 ping=1 myname=Fairy-Stockfish variants=\""  << vars << "\"" << Options << sync_endl << "feature done=1" << sync_endl;
**Engine crashes for consecutive sync_endl locks, must be replaced with:**
sync_cout << "feature setboard=1 usermove=1 time=1 memory=1 smp=1 colors=0 draw=0 name=0 sigint=0 ping=1 myname=Fairy-Stockfish variants=\""  << vars << "\"" << Options << sync_endl; sync_cout << "feature done=1" << sync_endl;

**Comment by ianfab** [comment]
Thanks for the report. Can you please give more details on the compiler error message, or if is is a runtime error, on how to reproduce it? The [appveyor builds](https://ci.appveyor.com/project/ianfab/fairy-stockfish) using Visual Studio 2017 seem to work smoothly.

However, unlocking the mutex twice is of course a bug, so I will fix it anyway, but having more details on how to reproduce it would still be nice, since this issue slipped through all the CI testing. I guess the issue is that the xboard protocol is not used there, so the problematic code was never executed.

**Comment by defrag1971** [comment]
I use Visual Studio 2015 sp3.
The compiling gives no error, but when in Winboard which uses Xboard protocol ver.2 (UCI works fine) the engine simply freezes when the command PROTOVER is issued.

In debug on that code line I get this:
**Visual C++ Runtime Library Debug error! abort() has been called.**

Greetings

**Comment by ianfab** [comment]
Thanks, should be fixed now. Would be nice if you can confirm that it works fine now.
