### ISSUE TITLE
Inquire about rules and usage of Janggi variant

### ISSUE THREAD

**Issue by kimpass23** [ianfab/Fairy-Stockfish#116]
Hello, I'm just a fan of Janggi in Pychess and have a few suggestions.
1. Repeated Error
 - There is an error that keeps repeating when AI can't back down
 - In Kakao Janggi, the most famous Janggi app among Koreans, there is a rule that cannot be repeated more than three times.

2. Bik jang Rule
- I know there is a Big Jang rule on Wiki, but in Korea, no one applies the Big Jang rule.

3. Usage of Fairy-Stockfish Engine
- Does "fairy-stockfish-largeboard_x86-64-bmi2.exe" include Janggi Variant?, I cannot find it when I did like below :

Download the Fairy-Stockfish executable from the latest release.
Download WinBoard and extract the zip archive.
Open the Winboard folder and double click the winboard.exe.
Click on Engines>Edit Engine List...
Add one line similar to "Fairy-SF" -fcp "C:\fairy-stockfish.exe" (adjust the path to where you put the .exe in step 1). Click on commit changes and OK.
Click on Engines>Load New 1st Engine... and double click on Fairy-SF.
Via File>New Variant... you should now be able to select variants supported by Fairy-Stockfish.
Troubleshooting
If the variant you are looking for is not in the list in step 7 (as not all variants are displayed), you can enforce a variant by changing the engine command from step 5 into, e.g., "Fairy-SF" /variant=janggi -fcp "C:\fairy-stockfish.exe" (replace janggi by the variant of choice), then redo step 6. The variant should be loaded automatically.

**Comment by ianfab** [comment]
Hi, I hope the replies below answer your questions:
1. The engine knows that repetitions are not allowed, but the interface does not prohibit the human player from playing them. If you had a game where the engine was at fault causing the repetition, please provide a link to the game.
2. Bikjang rules are used in professional tournament games, and this is the rule set we are using. This topic has already been discussed extensively.
3. Janggi is a very recent development in Fairy-Stockfish and there has not been an official release since Janggi was added, therefore you can not find it in the last release (Fairy-Stockfish 11).
