### ISSUE TITLE
Notation for Shogun Chess incorrect

### ISSUE THREAD

**Issue by CouchTomato87** [ianfab/Fairy-Stockfish#120]
Currently the notation system uses the most basic form, so now it's called queens "+F".

Also, Makruk is calling bishops "S." I'm not quite sure how the notation would work, but if anything, it's called a Bishop in English, so probably B rather than S.

**Comment by ianfab** [comment]
For Makruk the notation is consistent with e.g. cutechess, XBoard/Winboard, and pychess (GUI). I think it is not written anywhere, but I assume the "S" means "Silver", and since it is used in the FEN it is also used in notation. IMO there needs to be a very good reason to break with the existing de facto standard even if it might not be intuitive.

For Shogun there of course is no reference, so we need to decide for something. Currently shogi-style promotion always uses the `+` sign for both the promotion move as well as for moves of promoted pieces. If we decide to change that for SAN (or generally non-shogi notations), then to me it would make sense to consistently use pawn promotion style notation (e.g., Ba6=A, Ac8).

**Comment by CouchTomato87** [comment]
I think the pawn promotion style would be preferable in this case. In Shogi, most of the promoted pieces are the same, and the two that aren't can often have their own abbreviation (D and H). This system definitely wouldn't make sense for Shogun, where it would get quite messy.
