### ISSUE TITLE
How can I select "janggi" for Fairy-StockFish variant?

### ISSUE THREAD

**Issue by sprinter89** [ianfab/Fairy-Stockfish#128]
"Fairy-SF" /variant=janggi -fcp "C:\Users\sprinter89\Desktop\WinBoard\Fairy-StockFish\fairy-stockfish_x86-64.exe"
this one says "janggi is not supported by fairy-stockfish_x86-64"
how can I solve this problem?

**Comment by ianfab** [comment]
From where did you download the exe file? The last release (11) does not include Janggi yet, since it was added only very recently. I will probably publish an 11.1 release including Janggi support in the next weeks. If you want an up-to-date development version, you can try to compile Fairy-Stockfish from source.

**Comment by sprinter89** [comment]
thank you ianfab!

**Comment by sprinter89** [comment]
I'm currently on Windows so I'll be wait for that!
