### ISSUE TITLE
[Sittuyin] promotion rule

### ISSUE THREAD

**Issue by teakado** [ianfab/Fairy-Stockfish#14]
Thank you for adding Sittuyin support! 

I finally had a chance to do some testing, mainly by using some highly artificial positions to test rule conformity during promotion. The testing methodology was simple, involving obvious and enticing material incentives, to encourage promotion as long as the engine thinks it is legal to do so. 

I am happy to report that the current master branch seems to know most of the rules, although it still appears to be ignoring one: "The promotion shall not be made in the direct-attacking position to the opponent piece by newly-promoted general." (rule 3.9 c.4, page 8)

Specifically, it would try to promote with a fork on non-King pieces. But if the same move also attacks the opponent King, the engine knows about the "no checks, direct or discovered" rule, and avoids it. 

8/8/4r1r1/6fk/1R2P3/4N3/2N5/2KS4 w - - 0 1
PV: e4f5f (illegal attack forking two rooks with the new Fers)

But if the opponent King is also involved, a similar fork isn't attempted. 
8/8/4r1k1/6fr/1R2P3/4N3/2N5/2KS4 w - - 0 1
PV: e4e4f (legal promotion)

P.S.
I just realized that this might not be a bug, and probably a different interpretation that you made from the wording of the rules. But because this could potentially affect game-play, especially in positions where the engine might be relying on (or trying to avoid) variations which include winning/regaining material with forks upon promotion, I thought I'd report about this behavior. Thank you!

**Comment by ianfab** [comment]
Thanks for the thorough testing. My interpretation of this rule was that you may not capture by a promotion, since there does not seem to be any other paragraph stating something about this, but I agree that the wording rather indicates your interpretation of the rule. In cutechess and pychess these kind of attacking promotions also do not seem to be excluded, so @alwey and @gbtami might also be interested in this discussion.

One rule I definitely have not implemented yet is c.7, since claiming a draw by not making a move in a position where there are legal moves would require to add something like a passing move. Since this situation should be very rare, it does not have a high priority for me at the moment.

If you want to check whether the engine considers a move to be legal, you can also use perft (only via the command line, not in a GUI) instead of doing a search. E.g.:
```
setoption name UCI_Variant value sittuyin
position fen 8/8/4r1r1/6fk/1R2P3/4N3/2N5/2KS4 w - - 0 1
go perft 1
```
```
info string variant sittuyin files 8 ranks 8 pocket 6 template fairy startpos 8/8/4pppp/pppp4/4PPPP/PPPP4/8/8[KFRRSSNNkfrrssnn] w - - 0 1
e4e5: 1
e4d3f: 1
e4f3f: 1
e4e4f: 1
e4d5f: 1
e4f5f: 1
e3f1: 1
e3g2: 1
e3c4: 1
e3g4: 1
e3d5: 1
e3f5: 1
c2a1: 1
c2e1: 1
c2a3: 1
c2d4: 1
b4b1: 1
b4b2: 1
b4b3: 1
b4a4: 1
b4c4: 1
b4d4: 1
b4b5: 1
b4b6: 1
b4b7: 1
b4b8: 1
d1d2: 1
d1e2: 1
c1b1: 1
c1b2: 1
c1d2: 1

Nodes searched: 31
```

**Comment by gbtami** [comment]
@teakado thx a lot! Seems we all missed rule 3.9 c.4.

**Comment by alwey** [comment]
I was aware of this rule, and I interpreted it as prohibition to capture pieces by promotion.

**Comment by ianfab** [comment]
Since it is working as intended, I do not consider this a bug unless there is more evidence on how to interpret the wording of this rule. The rule 3.9 c.7 is also implemented now, so the Sittuyin rules should be completely supported.

If you encounter more unexpected behavior, feel free to re-open this or create a new issue.

**Comment by ianfab** [comment]
Reopening this due to new evidence regarding the interpretation of the rules, with answers provided by an arbiter: https://www.facebook.com/Myanmar-Sittuyin-105323654491347/

Summary:
* Promotions giving direct or discovery checks are prohibited
* **Promotions that cause the promoted piece to attack an opponent's piece are prohibited**
* Pawns that are allowed to promote do not attack the squares diagonally behind them (as the promotion can not capture), i.e., the opponent's king is allowed to move there.

**Comment by ianfab** [comment]
@alwey What is your opinion on changing this in cutechess as well? Shall I open an issue for it in the cutechess repo?

**Comment by alwey** [comment]
@ianfab Sorry for my comment being late.
Is following interpretation correct?

Promotions can neither capture nor give direct check (already implemented in cutechess).
Promotions cannot give **discovered** check.
Promotions cannot threaten opponent pieces directly by the next move.

The latter two aspects need implementation in cutechess.

**Comment by ianfab** [comment]
@alwey Yes, this interpretation is correct. Also see the adjusted perft tests in the above commit for testing:
https://github.com/ianfab/Fairy-Stockfish/commit/c55fea65e56223b0ce446661b5bc0043c90cea19#diff-79bc3d3d71d47c26c0606c8cdd8f2627L60-R62

**Comment by alwey** [comment]
Great, thank you! I just made a change to `SittuyinBoard::vIsLegalMove.` All of the referenced perft values match. I am going to push a PR.
