### ISSUE TITLE
Support holding command in UCI protocol

### ISSUE THREAD

**Issue by antoyo** [ianfab/Fairy-Stockfish#149]
Hi.
It seems the `holding` command to set the pieces in hand for e.g. bughouse is not in the UCI protocol.
Am I missing another way of doing that?
Thanks.

**Comment by ianfab** [comment]
Since the UCI protocol does not maintain the game state like the CECP does, I assume the canonical way of doing it for UCI is to send a new `position` command with the updated holdings.

However, I am not sure if this is very relevant, since I am not aware of any GUI supporting bughouse via the UCI protocol, therefore I currently also only support partner communication via CECP and not via UCI protocol. Or where is the question coming from?

**Comment by antoyo** [comment]
Thanks. I didn't know it was the way to go.
