### ISSUE TITLE
Missing ffishjs features

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#177]
Some more Fairy stuff would be useful to be exposed for pychess client side analysis:
- [ ] setoption(name, value) to set variants.ini path
- [ ] Board.isCheck() to style king in check
- [ ] Board.isBikjang() to style kings in bikjang
- [ ] Board.movesToSan(movelist, notation) to convert analysis PV to SAN movelist
- [ ] Board.san_move() should accept notation parameter also (now NOTATION_SAN is hardwired)

**Comment by gbtami** [comment]
@QueensGambit I started to use the ES6 module compiled by myself in https://github.com/gbtami/pychess-variants/blob/master/client/analysisCtrl.ts#L277
Is it possible to add it also to npm? Or is that need another npm package?

**Comment by QueensGambit** [comment]
Hi @gbtami , I mentioned the possibility of publishing an ES6 module in https://github.com/ianfab/Fairy-Stockfish/pull/174.
I didn't find a way yet to export both versions as a single package.
I'd prefer having a single package of ffish on npm as a ES6 module to avoid confusion and reduce maintenance effort.

The reason why it is currently published as ES5 is because I was unable to load the ES6 module with `esm` or `babel` in Node.js to run the test-suite:
```javascript
$ node -r esm index
both async and sync fetching of the wasm failed
both async and sync fetching of the wasm failed
Test server of ffish.js listening on port 8000.
http://127.0.0.1:8000/
failed to asynchronously prepare wasm: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
(node:1500) UnhandledPromiseRejectionWarning: RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (~/Fairy-Stockfish/tests/js/ffish.js:9:10332)
    at ~/Fairy-Stockfish/tests/js/ffish.js:9:11861
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
(node:1500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
If you find a way to do this we can change to ES6.
In case this doesn't work we can consider publishing an additional package called **ffish-es6.js**.

Regarding your requested method:
```javascript
 Board.movesToSan(movelist, notation) to convert analysis PV to SAN movelist
```
Java-Script arrays are not part of the [**built-in type conversions**](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions) of embind.

Originally, I tried using
```javascript
register_vector<string>("VectorString");
```
for returning the legal move list but found it to be slower than returning a string and splitting it (https://github.com/ianfab/Fairy-Stockfish/pull/158).
Moreover, `VectorString` is not native java script.

Passing and returning an array should be possible but it looks to me that you need to manage an [additional memory buffer for it on the java script side](https://stackoverflow.com/questions/41875728/pass-a-javascript-array-as-argument-to-a-webassembly-function).
Probably, passing and returning a string with `" "` as delimiter is similarly fast and more convenient.

**Comment by gbtami** [comment]
@QueensGambit I think passing and returning a string with " " as delimiter is Ok for UCI and SAN movelist.

**Comment by gbtami** [comment]
@QueensGambit another missing feature would be important to add, make moveStack of the Board available.
