### ISSUE TITLE
Setoption error

### ISSUE THREAD

**Issue by wawahuy** [ianfab/Fairy-Stockfish#217]
Why?
Version: 11.2 bmi2
It new version error but before dont error
![image](https://user-images.githubusercontent.com/16779694/102174766-c1c58880-3ed0-11eb-8da1-8e3ff6393bb4.png)

**Comment by ianfab** [comment]
The message about large pages is not an error, just an information, so that should not be a problem. However, as far as I can see you are using the UCCI protocol, so I guess you want to play Xiangqi. For this to work you need to download the large-board version (e.g., fairy-stockfish-largeboard_x86-64-bmi2.exe), because the normal version (e.g., fairy-stockfish_x86-64-bmi2.exe) does not include variants with board sizes >8x8 such as Xiangqi.

Let me know if this solves your problem, or otherwise please give some more details about the error you are encountering.

**Comment by wawahuy** [comment]
Sorry, I'm really stupid. I downloaded the correct old version, but I chose wrong this upgrade
V11.2.
Does this version 11.2 support NNUE?

**Comment by ianfab** [comment]
No, 11.2 does not support NNUE yet. If you are referring to NNUE for Xiangqi, the current development version also does not support it for Xiangqi yet, because >8x8 boards are not working with NNUE yet, but I am working on it. I however trained some networks for Minixiangqi (7x7) to already see how well NNUE might potentially later work for Xiangqi, see https://www.patreon.com/ianfab.
