### ISSUE TITLE
S-chess

### ISSUE THREAD

**Issue by gbtami** [ianfab/Fairy-Stockfish#23]
It would be nice to have S-chess support in Fairy-Stockfish.
Similar to Makruk, you "just" have to merge it from Seirawan-Stockfish :wink:

**Comment by ianfab** [comment]
S-Chess was on my agenda from the very beginning, since actually the idea for this fork originated from questioning myself why I should maintain Shatranj, Makruk, and S-Chess in three different forks if they could just be put into one which would also allow to easily support more variants.

However, gating unfortunately does not integrate that well with some other features, especially if you want to allow combination of gating with other special move types such as shogi-like piece promotion. Excluding such extensions beyond S-Chess makes it more feasible, but it still does not fit in that easily.

Nevertheless, S-Chess is still one of the main candidates for the next variants to be added.

**Comment by ianfab** [comment]
I reconsidered the difficulties of the S-Chess implementation based on the current code and found that it is actually not as problematic as I thought. I added a [first implementation](https://github.com/ianfab/Fairy-Stockfish/commit/fc0d0f3aea3a690cf14d6c57ae91ac5f4fc8c69e) which at least produces the correct `perft 5` value, but apart from that I did not do any testing yet.

**Comment by gbtami** [comment]
Thx! Will test it on https://pychess-variants.herokuapp.com/ soon.

**Comment by ianfab** [comment]
@gbtami I just pushed one fix for a bug that caused occasional segfaults. Now a ten-game match against Sjaak II in cutechess worked without crashes.

**Comment by ianfab** [comment]
Performance seems quite good already without any adaptions for search or evaluation:
```
Score of Fairy-Stockfish vs Seirawan-Stockfish: 7 - 38 - 5 [0.190]
Elo difference: -251.89 +/- 122.26, LOS: 0.00 %, DrawRatio: 10.0 %
```

**Comment by gbtami** [comment]
Deployed to pychess-variants site. Seems to work well so far.
