### ISSUE TITLE
will the (older) neural network be freely available eventually on Github?

### ISSUE THREAD

**Issue by SGQuek** [ianfab/Fairy-Stockfish#231]
to @ianfab 
The stockfish comes with an nnue by default, and their nnue has been made freely available for download.

So will the (older) nnue for fairy-stockfish be made freely available too?

**Comment by ianfab** [comment]
In general I plan to make NNUE networks publicly available after some time, but supporters on https://www.patreon.com/ianfab get exclusive early access to new networks for some (undefined) period of time as a reward for their contribution, since this project consumes quite some time and money for development and can only sustain through donations.
