### ISSUE TITLE
janggi illegal move (2)

### ISSUE THREAD

**Issue by d4soft2021** [ianfab/Fairy-Stockfish#261]
my friend setup /janggimodern
I am using /variant=janggicasual

my friend created PGN file = sample.PGN
I created PGN =  my.PGN (my program converted from DOSA .gib to PGN file)
I do not fully understand PGN format, though my friend's stock fish says illegal move about my.PGN
My stock fish says illegal move about sample.PGN
Upto 14 move, same pieces move same position. (2 files are same game recording)
I upload 2 files, change extension PGN-->txt (not allowed upload PGN file)
Please review them.
Thank you again
[my.txt](https://github.com/ianfab/Fairy-Stockfish/files/6014169/my.txt)
[sample.txt](https://github.com/ianfab/Fairy-Stockfish/files/6014171/sample.txt)

**Comment by ianfab** [comment]
For me both PGNs work fine when loading them with Fairy-SF11.2 and a corresponding XBoard (the Linux equivalent of Winboard)  version that is compatible to it. Your converted PGN has some redundant SAN disambiguation in it, but XBoard/Winboard seems to handle that fine. Out of curiosity, what do you use for converting gib to PGN?

However, with the most recent XBoard/Winboard and Fairy-Stockfish versions both PGNs do not load at all due to the aforementioned changes in both XBoard/Winboard and Fairy-Stockfish, which causes the piece letters of horse (N->H) and elephant (B->E) to change, and hence would also need to be changed in the PGN. This is just something to consider as soon as you upgrade to the latest version, but as mentioned, with older versions your PGNs should in principle work fine. However, I would still recommend to upgrade.

I suspect that there might still be a discrepancy in the Winboard and Fairy-Stockfish versions or settings you and your friend are using, because otherwise they should be compatible. One relevant setting in Winboard with respect to move validation is `Options`>`General...`>`Test Legality`, but I am not sure if changing this will fix your issue.

If after that it still does not work, you can maybe ping `@HGMuller` here, who is the author of Winboard, or ask in his forum http://www.open-aurec.com/wbforum/.

**Comment by d4soft2021** [comment]
Thank you.

I upload new issue today as follows
-----------------------------------------
protocol between win board and stock-fish
I upload 2 issues recently.
Thank you for quick response.
I made program converting .gib file to .pgn files.
Because hundreds thousands of gib files on internet, gib files are very popular in Korea.
Many people want those janggi records to be reviewed via stock-fish from different view points.

Finally I want to develop the service such as best movement on gib point or stock point.
The service is web-base oriented, I planned.
in order to do that, I need to know protocol between winboard and stock.
I reviewed winboard document, and I roughly read your stock-fish source, but not enough information.
I would appreciate if you provide the information about protocols.
I tried to compile winboard source, not success because it was written C language long time ago.
Your stock-source is OK, in my VS2013 C++.
Please help me.


closeed issue due to thread ?
what does it mean ?
     On Saturday, February 20, 2021, 05:11:47 AM EST, Fabian Fichter <notifications@github.com> wrote:  
 
 


For me both PGNs work fine when loading them with Fairy-SF11.2 and a corresponding XBoard (the Linux equivalent of Winboard) version that is compatible to it. Your converted PGN has some redundant SAN disambiguation in it, but XBoard/Winboard seems to handle that fine. Out of curiosity, what do you use for converting gib to PGN?

However, with the most recent XBoard/Winboard and Fairy-Stockfish versions both PGNs do not load at all due to the aforementioned changes in both XBoard/Winboard and Fairy-Stockfish, which causes the piece letters of horse (N->H) and elephant (B->E) to change, and hence would also need to be changed in the PGN. This is just something to consider as soon as you upgrade to the latest version, but as mentioned, with older versions your PGNs should in principle work fine. However, I would still recommend to upgrade.

I suspect that there might still be a discrepancy in the Winboard and Fairy-Stockfish versions or settings you and your friend are using, because otherwise they should be compatible. One relevant setting in Winboard with respect to move validation is Options>General...>Test Legality, but I am not sure if changing this will fix your issue.

If after that it still does not work, you can maybe ping @HGMuller here, who is the author of Winboard, or ask in his forum http://www.open-aurec.com/wbforum/.

**Comment by ianfab** [comment]
> closeed issue due to thread ?
> what does it mean ?
I just closed the original issue/thread because I assumed the old one is superceded by this one and closed it to keep the open issue list tidy, because having more than one thread for one topic can be slightly confusing.

**Comment by ianfab** [comment]
@d4soft2021 Has this issue been solved?
