### ISSUE TITLE
janggi, /variant=janggicasual

### ISSUE THREAD

**Issue by d4soft2021** [ianfab/Fairy-Stockfish#272]
where the janggicasual is defined ? winboard or fairy -stockfish ?
I compiled the source of fairy-stock from github source.
I tried to test it from winboard setup, it come up error message "not recognized (janggicasual)",
of course no ploblem on compiled exe file from github x86-largeboard.

I wonder (janggicasual) is defined in winboard ? or fairy-stock ?
Thank you.

**Comment by ianfab** [comment]
The Janggi variants (janggicasual, janggimodern, janggitraditional) are defined in Fairy-Stockfish, see https://github.com/ianfab/Fairy-Stockfish/blob/4f464fce39b8db5ea039d7e84c021cd16dfaba9b/src/variant.cpp#L971-L995

Winboard does not know about these variants, but the CECP protocol gives the engine a way to inform the GUI about (some aspects of) the rules of the game.

Therefore, if you want to start a game in such a variant, an engine supporting this variant needs to be loaded. When compiling Fairy-Stockfish yourself from sources, did you add `largeboards=yes` as described in https://github.com/ianfab/Fairy-Stockfish/wiki/Compiling-Fairy-Stockfish#compiling-version-for-large-boards ? It might be that you compiled the non-largeboard version, which does not include Janggi. You can also check this from the displayed engine name, since that should include `LB` (e.g., Fairy-Stockfish 070321 LB).

**Comment by d4soft2021** [comment]
Thank you for your kind detailed information.
It will help a lot. I will try it again.

James Lee 
Mar 7,2021
     On Sunday, March 7, 2021, 08:39:09 AM EST, Fabian Fichter <notifications@github.com> wrote:  
 
 


The Janggi variants (janggicasual, janggimodern, janggitraditional) are defined in Fairy-Stockfish, see https://github.com/ianfab/Fairy-Stockfish/blob/4f464fce39b8db5ea039d7e84c021cd16dfaba9b/src/variant.cpp#L971-L995

Winboard does not know about these variants, but the CECP protocol gives the engine a way to inform the GUI about (some aspects of) the rules of the game.

Therefore, if you want to start a game in such a variant, an engine supporting this variant needs to be loaded. When compiling Fairy-Stockfish yourself from sources, did you add largeboards=yes as described in https://github.com/ianfab/Fairy-Stockfish/wiki/Compiling-Fairy-Stockfish#compiling-version-for-large-boards ? It might be that you compiled the non-largeboard version, which does not include Janggi. You can also check this from the displayed engine name, since that should include LB (e.g., Fairy-Stockfish 070321 LB).
