### ISSUE TITLE
Possibility to use foreign nets?

### ISSUE THREAD

**Issue by mtaktikos** [ianfab/Fairy-Stockfish#326]
On the site 
http://dl.fbaipublicfiles.com/polygames/checkpoints/list.txt 

there are many public nets in checkpoint-format, including Breakthrough, Othello, Minishogi, Kyotoshogi - games which are already implemented in Fairy-SF.

In
https://github.com/glinscott/nnue-pytorch 
chapter "Export a network", we can read:
"Using either a checkpoint (.ckpt) or serialized model (.pt), you can export to SF NNUE format. This will convert last.ckpt to nn.nnue, which you can load directly in SF."
Can this be understood as an easy way to extract SF NNUE files from the above mentioned nets?

**Comment by ianfab** [comment]
I am not that much into polygames, but I assume that they use a very different network architecture, which likely can't be supported. Therefore, even if they also use pytorch and the same format to create checkpoints of the training, we unfortunately can not really make direct use of that.

The only way to make use of other networks would be to generate training data with them and then train a supported network architecture using that training data. However, I would preferably try with self-training first (as soon as these variants are supported with NNUE), because I assume that this should result in at least as strong networks as doing supervised training with foreign nets, and its of course more original. The only exception might be very complex variants where the gap between classical and NN evaluation is huge and reinforcement learning might therefore take very long, e.g., Go, shogi, etc. Of the variants you mentioned Othello might be the only variant falling into this category, but it also is not overly complex, so maybe training would still progress quickly.
