### ISSUE TITLE
Centaur Chess

### ISSUE THREAD

**Issue by Nordlandia** [ianfab/Fairy-Stockfish#33]
10x8 chess board with a brand new fairy piece. The "Centaur" has two possible moves It can move one square in any direction or It can move like a Knight.

Centaur Chess is available to play at Green Chess. 

https://www.chessvariants.com/large.dir/contest/royalcourt.html

**Comment by ianfab** [comment]
@Nordlandia Do you know any other variant that uses the Centaur?

I am asking because it is on the one hand quite trivial to support the Centaur piece (and then out-of-the-box also Centaur chess via the configuration file), but on the other hand currently the addition of new piece types still requires them to be added to the fixed list of supported pieces which is limited to 64. Therefore, in contrast to the addition of new variants, I am a bit hesitant with the addition of new pieces unless they are used by a popular variant or at least several variants.

Ultimately, it would of course be best if one could configure pieces just like variants via configuration, but this will take time.

**Comment by Nordlandia** [comment]
There is some information about this piece available at this link: https://www.chessvariants.com/piececlopedia.dir/centaur.html

**Comment by ianfab** [comment]
Thanks for the info. Unfortunately, it seems like all of the variants in the list for the Centaur would not work at the moment, because they have special rules with regards to castling, promotion, or new pieces. I will probably add the Centaur at a later point, so I will keep this open.

**Comment by Nordlandia** [comment]
Royal Court or Centaur Chess uses the non-royal version of the Centaur piece. There is no castling, except for promotion to Centaur is valid.

**Comment by ianfab** [comment]
Sorry, my wording was a bit imprecise. I meant that all variants except for Centaur chess have additional special rules, Centaur chess itself would of course work as mentioned before.

**Comment by Nordlandia** [comment]
Is Perfect Chess support feasible or doable in the long run?

**Comment by ianfab** [comment]
Yes, it is. I have the castling with non-rook pieces on my list for quite a while already (see #1, other variants using that would be New Zealand, biform, thinktank, and loonybird), but so far there have always been many other features with higher priority (Shogi, S-Chess, variant configuration, etc.), so I did not get to it. I am pretty sure I will implement it sooner or later, it just takes time in the current one-man project state.

**Comment by Nordlandia** [comment]
Is it allowed to Castle with Chancellor in Capablanca Random Chess?

**Comment by ianfab** [comment]
No, only with rooks. The castling rules are basically the same as in chess960.

**Comment by Nordlandia** [comment]
It is not allowed to castle in crazyhouse with dropped rooks. I don't know the exact reason for not being able to do so.

**Comment by ianfab** [comment]
In which way is this relevant for this topic?

**Comment by Nordlandia** [comment]
Good point =)

**Comment by CouchTomato87** [comment]
For what it's worth, would also like to have the centaur for shogun chess :)
