### ISSUE TITLE
S-Chess - stuck gated material not evaluated properly

### ISSUE THREAD

**Issue by abgros** [ianfab/Fairy-Stockfish#353]
To show what I mean, consider the FEN

rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR[HEhe] w KQkqbcdfg - 0 1

This position is completely lost for white, as they are unable to bring any of their gated pieces into the game. However, the engine shows the position as being roughly equal (+40 cp after depth 22)

**Comment by abgros** [comment]
Correction: white is apparently able to bring one of their pieces during castling. However white is still losing by a large margin.

**Comment by ianfab** [comment]
Thanks. This has also been discussed in https://github.com/ianfab/Fairy-Stockfish/issues/160. As mentioned there, there is not too much one can do about that apart from trying to find Elo gaining patches that improve it, and everyone is of course invited to do that. Considering that attempts to mitigate this behavior so far only resulted in a very small Elo gain, and simple patches that eliminate this problem entirely completely failed (they would regress playing strength), it has to be assumed that this is just an artifact not much relevant for playing strength in practice.

As you mentioned the above FEN isn't a good example though, since white still has three gates (e1, h1, a1) available.
