### ISSUE TITLE
Confusion about the "kingType" parameter when reading from variants.ini

### ISSUE THREAD

**Issue by thearst3rd** [ianfab/Fairy-Stockfish#363]
I hope you don't mind my onslaught of PRs/issues :)

I'm a bit confused about the how "kingType" works when reading from variants.ini. This is partly because there are no examples of its use in the given variants.ini.

Lets say I want to make a variant that is the same as chess, except the king moves as a centaur. To do this in C++ is quite easy, it looks like this:

```c++
    Variant* centaurking_variant() {
        Variant* v = chess_variant_base()->init();
        v->kingType = CENTAUR;
        return v;
    }
```

I am trying to figure out the equivalent way of doing such a variant in ini format. I'm not sure what to set the kingType as - it parses it by reading in the character from the pieceToChar string - but there isn't a piece character for centaur. I've been trying stuff like:

```
[centaurking:chess]
centaur = c
kingType = c
```

~~But that hasn't worked (the king still moves like a king)~~_(edit: it works, I had a typo before, now fixed)_. Additionally, it's defining a "centaur" piece mapped to the letter c that I'm not planning on using. It seems like "kingType" does two different things in c++ and ini - I'm not sure if this is a bug/missing feature, or if I am just misunderstanding something.

Let me know if I did something wrong, or if there is actually something that needs to be changed in Fairy-Stockfish.

**Comment by ianfab** [comment]
Yes, your understanding is correct. The issue is that in the parsing Fairy-SF needs some way to refer to the piece types. For other fields this for convenience is done via the piece letter (instead of e.g. the full name), and for that reason I took it over for the `kingType` as well. However, as you mentioned in contrast to other fields this type does not necessarily need to be defined, which is confusing and makes it impossible to define the variant in a minimal way (i.e., without a superfluous piece type).

Now that piece types are configurable, one idea would be to directly allow to configure the Betza notation either in the `king` or the `kingType` field. One issue with that though is that in contrast to the configurable piece slots, the king attacks may not be overridden because (if I remember correctly) some places use king attacks as a synonym for a ring of 8 squares, so one would still likely need to use up a slot for storing the movement which would then need to be blocked for other pieces. Just thinking out loud, not sure yet what would be a good solution. But I definitely agree that the current behavior is not nice here.

**Comment by thearst3rd** [comment]
> Edit: Regarding your INI, you need to use = instead of colons to assign the values.

Wow... I cannot believe I didn't notice that - I guess I had JSON on my mind :) After changing them to equal signs, it worked as intended. Maybe there should be some way that gets caught when doing `fairy-stockfish check`, since that didn't complain about any errors.

I could have swore I had an issue earlier this week with the "kingType" property in a different variant I was fiddling with, at some point I even got F-SF to segfault. But using the steps above (that is, defining an extra unused piece type and setting the kingType to that) seems to be working there too. Surely I must have tried that before but alas :) I want to see if I can find/replicate any errors using the latest build, and if I can, I'll bring them up here.

**Comment by ianfab** [comment]
> Maybe there should be some way that gets caught when doing fairy-stockfish check, since that didn't complain about any errors.

So far it only checks for validity of the content, not the syntax. During parsing it simply ignores any line that is a comment or does not contain an equals sign, see https://github.com/ianfab/Fairy-Stockfish/blob/4f3885107e990adb97f37dcc44b0998bcf5972d5/src/variant.cpp#L1487

so we could potentially report here any lines that are neither blank, nor comment, nor valid.

**Comment by ianfab** [comment]
To summarize, to my understanding there are two things that could potentially be done to address the topics mentioned here
* [ ] Simplify definition of kingType, not requiring definition of fake piece type to describe king movement.
* [ ] Validate syntax of variants.ini

As mentioned the second point is not trivial, and might require reserving a piece slot for the configurable king. Suggestions for alternative solutions are of course welcome.

**Comment by thearst3rd** [comment]
The second one I think is significant enough to warrant its own issue, that seems out of scope of a "confusion about kingType" issue.

Regarding how I think the kingType could work in the variants.ini - one way that seems simple enough (on the usability side) is to parse for one of the piece names in the variants.ini rather than for an existing piece letter. For example, my "centuarking" variant would be defined as follows:

```
[centaurking:chess]
kingType = centaur
```

Implementation-wise, that would require the creation of a new Option Type that needs to be parsed, something like

```
### Option types
...
# [PieceType]: a piece type [letters defined for pieces, e.g., p]   <-- this one already exists
# [PieceMovements]: the name of a pre-defined piece type [e.g., rook, king]
```

The pieces names as strings already exist and are defined in piece.cpp (so that you can say `archbishop = a` etc), so I think that is feasible to add to the parsing. This means that custom pieces aren't supported, but it seems they aren't anyway?

https://github.com/ianfab/Fairy-Stockfish/blob/1aa783e32d58973e88f5d77aaf3d8f667b868339/src/parser.cpp#L418-L428

Maybe "PieceType" should change to "PieceLetter" and the new one could be called "PieceType"? That seems to be getting too complex/confusing/breaking for this small change. Additionally, this whole thing is a breaking change and any variant.ini which uses the currently existing `kingType` will no longer work.

Another thing that could be used to clear up the confusion is to just include an example in variants.ini where the kingType parameter is used. Searching for `kingType` in the the variants.ini in this repository - as well as https://github.com/gbtami/pychess-variants/blob/master/variants.ini - doesn't turn up any results (other than the comment at the start). Just having an example might help people who want to use the property know how it works.

**Comment by ianfab** [comment]
> The second one I think is significant enough to warrant its own issue, that seems out of scope of a "confusion about kingType" issue.

I agree. Feel free to create a separate issue for it if you think it should be considered.

> Regarding how I think the kingType could work in the variants.ini - one way that seems simple enough (on the usability side) is to parse for one of the piece names in the variants.ini rather than for an existing piece letter.

> The pieces names as strings already exist and are defined in piece.cpp (so that you can say `archbishop = a` etc), so I think that is feasible to add to the parsing. This means that custom pieces aren't supported, but it seems they aren't anyway?

Yes, I thought about that, but as you mentioned that does not solve it for custom pieces. The above mentioned code does not mean that custom pieces are not supported as king types, but only that we can not validate if the given custom piece is supported. This is because hoppers and lame leapers are not allowed as kings (due to non-mutual and discovered checks), neither built-in nor configured, and we need to know the exact movement of the piece to determine if that is the case, but custom pieces are only initialized when loading the variant, which is after the parsing. Therefore this limitation can only be checked for built-in pieces. Suggestions how to make this more clear in the comment are of course welcome (also for comments in the code base in general, since main authors are not always the best at judging if a commment is clear enough).

> Another thing that could be used to clear up the confusion is to just include an example in variants.ini where the kingType parameter is used. Searching for `kingType` in the the variants.ini in this repository - as well as https://github.com/gbtami/pychess-variants/blob/master/variants.ini - doesn't turn up any results (other than the comment at the start). Just having an example might help people who want to use the property know how it works.

Yes, it would be helpful to have a good coverage of configuration options in the examples, but I did not systematically check yet which ones are missing. If you have a good suggestion for a variant that could be used for the `kingType`, please let me know, or raise a PR of course :).
