### ISSUE TITLE
Does Fairy-Stockfish support Mac osx?

### ISSUE THREAD

**Issue by JernejHenigman** [ianfab/Fairy-Stockfish#391]
Hi,

I know that there are Fairy-Stockfish versions for both Windows and Linux. But is there version for OSX as well?

Regards
Jernej

**Comment by ianfab** [comment]
Hi. Yes, Fairy-Stockfish supports the same platforms as official Stockfish, so it should also work on OSX. I am just not very familiar with cross compilation from Linux to Mac, which is why I do not provide release binaries. You can check https://github.com/ianfab/Fairy-Stockfish/wiki/Compiling-Fairy-Stockfish#compiling-on-macos, I hope that works for you.

**Comment by JernejHenigman** [comment]
Thank you. I find the solution that does not involve using mac os for this problem anymore. We can close the issue at this point.
