### ISSUE TITLE
Hope to have a release of xiangqi training tool

### ISSUE THREAD

**Issue by shuangqiao999** [ianfab/Fairy-Stockfish#457]
Hello! Can we make a release of xiangqi training tool? Because many xiangqi players do not have programming ability

**Comment by ianfab** [comment]
Hi. Due to its hardware and software requirements the training code isn't that easy to bundle into an end user friendly application. On the other that also isn't necessarily required, since not everyone needs to train his own NNUE network, but it is sufficient if a few people train the networks that can then be used by everyone.

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
