### ISSUE TITLE
Why are fairy stockfish is not large file 

### ISSUE THREAD

**Issue by HeroRebor** [ianfab/Fairy-Stockfish#470]
I mean to say stockfish is large file of 45 mb but why fairy stockfish is not so large file
And is there any possibility for future to make standard of fairy stockfish more better?

**Comment by ianfab** [comment]
Having large binaries is an inconvenience and not a feature, and the usability improvement of having the standard chess net built-in is negligible for Fairy-SF since standard chess is more or less an irrelevant feature of Fairy-SF, so it would be a waste to increase the binary size by more than an order of magnitude for something that is of almost no use. Relevant releases with built-in variant NNUE are available at https://github.com/ianfab/Fairy-Stockfish-NNUE.

**Comment by HeroRebor** [comment]
Hiw can we make variant book?

**Comment by ianfab** [comment]
This isn't a lichess bot help forum, but a place for discussion about Fairy-Stockfish development.

**Comment by HeroRebor** [comment]
Ok I just asked because its variant np
