### ISSUE TITLE
Please Jangqi NNUE update relese ?

### ISSUE THREAD

**Issue by kimeundong** [ianfab/Fairy-Stockfish#496]
New Janggi NNUE

**Comment by ianfab** [comment]
You can always find the latest Janggi NNUE release at https://github.com/fairy-stockfish/Fairy-Stockfish-NNUE/releases, i.e., currently it still is https://github.com/fairy-stockfish/Fairy-Stockfish-NNUE/releases/tag/janggi-ffbf1d95cea2. Since the training code is open source, see https://github.com/fairy-stockfish/variant-nnue-pytorch, anyone can try his luck at training a stronger NNUE. If and when someone succeeds in improving it, it will of course be made available at the aforementioned place.

**Comment by ianfab** [comment]
@kimeundong I already answered your question here, so please don't spam other discussions with this question. Repeatedly asking it won't change the answer. An update will be ready when it will be ready. This is a hobby open source project and there are no fixed release schedules. If you want to push this project forward, then do it by [contributing](https://github.com/ianfab/Fairy-Stockfish/wiki/Contributing), not by demanding.
