### ISSUE TITLE
immobilityIllegal not Working Properly

### ISSUE THREAD

**Issue by PraseodymiumSpike** [ianfab/Fairy-Stockfish#521]
[cannonshogi:shogi]

shogiPawn = -
soldier = p
dropNoDoubled = -
cannon = u
janggiCannon = a
customPiece1 = c:mBcpB
customPiece2 = i:pB
customPiece3 = w:RpRFpA
customPiece4 = f:BpBWpD
promotedPieceType = u:w a:w c:f i:f
startFen = lnsgkgsnl/1rci1uab1/p1p1p1p1p/9/9/9/P1P1P1P1P/1BAU1ICR1/LNSGKGSNL

does not allow 1. I-75 despite the Iron cannon not being immobile in that position (or any position, for that matter, as it can move in any diagonal direction)

**Comment by ianfab** [comment]
FYI, I transferred the issue to the Fairy-SF repository, because the game rule logic in all Fairy-SF dependent projects (such as fairyground, fairyfishgui, liground, as well as pychess) uses the Fairy-SF code, so such issues need to be addressed here. I will have a look at a later point. I already pushed some experimental code yesterday related to this: https://github.com/ianfab/Fairy-Stockfish/tree/permanent_immobility
