### ISSUE TITLE
Double-Move Chess

### ISSUE THREAD

**Issue by lbordowitz** [ianfab/Fairy-Stockfish#529]
Implement the [double-move chess variant](https://www.chessvariants.com/multimove.dir/doublemove.html). 

Each player is given two moves per turn. This variant has no check, and the object is to capture the opponent's king. 

This is related to #528 , where each player gets two moves as well (although in duck chess, on the second move, the player is restricted to moving only the duck piece). More generally, this multi-move paradigm may pave the way for implementing many other chess variants than just those two.

**Comment by ianfab** [comment]
See #343 and commits referenced there regarding experimental support for multimove variants.

However, this is just a workaround and likely there won't ever be more than just this workaround in Fairy-Stockfish since proper support for multimove variants would require a fundamentally different design. The branch with the workaround should however in principle be functional, so people can feel free to experiment with it.

**Comment by lbordowitz** [comment]
Closing as duplicate, in preference for tracking in #343
