### ISSUE TITLE
Non-rectangular boards, boards with holes

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#53]
Exclusion of squares from the board would allow to support non-rectangular boards and boards with holes.

Links:
* https://www.gnu.org/software/xboard/whats_new/4.9.0/index.html#tag-B5
* https://github.com/ianfab/Fairy-Stockfish/issues/1#issuecomment-417918488

**Comment by HGMuller** [comment]
Note that XBoard supports inaccessible squares in FEN as an asterisk * . So Omega Chess would be a 12x12 variant there, with edges (not corners) inaccessible.

**Comment by alwey** [comment]
There is a distinction between inaccessible squares. One type of squares can neither be passed nor be occupied. Those are denoted by an asterisk `*` in xboard (and subsequently, in cutechess), e.g. in Omega Chess or Gustav III Chess. Then there are squares that cannot be occupied but can be crossed over by sliders or hoppers, e.g. some boundary squares in  Cheshire Cat Chess (by V R. Parton) where every square that is left by a piece "disappears". I suggest using a different symbol for that in FEN, e.g. a dot `.` which looks sufficiently neutral.

**Comment by alwey** [comment]
There is a distinction between inaccessible squares. One type of squares can neither be traversed nor occupied. Those are denoted by an asterisk `*` in xboard (and subsequently, in cutechess), e.g. in Omega Chess or Gustav III Chess. Then there are squares that cannot be occupied but can be crossed over by sliders or hoppers, e.g. some boundary squares in  Cheshire Cat Chess (by V R. Parton) where every square that is left by a piece "disappears". I suggest using a different symbol for that in FEN, e.g. a dot `.` which looks sufficiently neutral.

**Comment by alwey** [comment]
There is a distinction between inaccessible squares. One type of squares can neither be traversed nor occupied. Those are denoted by an asterisk `*` in xboard (and subsequently, in cutechess), e.g. some boundary squares in Omega Chess or Gustav III Chess. Then there are squares that cannot be occupied but can be crossed over by sliders or hoppers, e.g.  in  Cheshire Cat Chess (by V R. Parton) where every square that is left by a piece "disappears". I suggest using a different symbol for that in FEN, e.g. a dot `.` which looks sufficiently neutral.

**Comment by HGMuller** [comment]
XBoard currently only supports wall-type squares. The use case was indeed for padding non-rectanglar boards. Games like Chessire Cat and Voidrider seemed a bit too exotic to implement special display features for those.  GUIs can handle those without any problems; it is only that the user cannot see which squares are inaccessible.

I can imagine more types of such square, btw: you could also have squares that behave like they were occupied by an uncapturable piece: hoppers could hop over those, but sliders could not pass through them.

About the period in FEN: I am still a bit in doubt. XBoard supports the concept of 'dressed letters' as piece ID in FEN, which means letter + punctuation. Currently only quote and exclamation point are accepted as the punctuation character, but I would like to reserve a few characters in case we need to extend the number of piece types occurring in one variant. In particular the narrow characters. So my preference for board holes goes to something bulky, like underscore, number sign or at sign.

**Comment by alwey** [comment]
> So my preference for board holes goes to something bulky, like underscore, number sign or at sign.

Ah, yes, underscore ` _` seems to be both neutral and visually appropriate, so I would go with that.

> I can imagine more types of such square, btw: you could also have squares that behave like they were occupied by an uncapturable piece: hoppers could hop over those, but sliders could not pass through them.

I had similar distinction in mind after thinking about my message above (low and high wall types).

In cutechess, sliders cannot traverse wall pieces. Hoppers can, because a hopper only tests the validity of the target square. Currently this behaviour is not obvious from the start in any variant. Knights can move around wall squares in Gustav III Chess anyway. Rooks, Queens and Adjutant Generals cannot pass wall squares. If more asterisks are added to the setup FEN of `gustav3`, then the behaviour is exposed in detail.

**Comment by HGMuller** [comment]
OK, underscore it is!

BTW, an alternative to distinguishing various types of walls would be to describe this as a property of the move of the pieces that have to deal with them. I am leaning towards adding a modifier **o** to the Betza notation, meaning 'can land outside the board'. (For non-final legs of a multi-leg move, obviously; eventually the piece must land on the board, and an **o** in the final leg can keep its original Betza meaning of wrapping.) This would fo instance allow you to probe for proximity of a board edge, e.g. **oabQ** would be a Queen that (for non-captures) can only land on an edge square. It would also allow description of pieces like the Ultima Withdrawer: **cabyafmK** would decribe the capture move as a multi-leg detour, but against an edge the detour would not be allowed. And you cannot add a normal **mQ** to cover that case, because that would make the capture optional. Making the first leg **co** instead of **c** would solve that.

With such an **o** modifier it would be possible to define sliders that could move over 'voids' as hoppers that only hop voids (e.g. **QoafQ**), and hoppers that also can use voids as a mount (e.g. **mRpoafcR**). And then you would need only one type of void.
