### ISSUE TITLE
Duck chess implementation

### ISSUE THREAD

**Issue by CrazDuck** [ianfab/Fairy-Stockfish#531]
I have recently started making a 'Duck Chess' app, where you can play duckchess against my trash AI, or against a friend. I wanted to add a 'Game Analysis' page to my app, where you can use FairyStockfish to analyze your duckchess games. I am very new to this repository, so I dont really understand how this could be done. 

The first obvious issue was how to support the duck piece, it isn't whites, and it isn't black. #528 references this issue. How would both sides be able to move it? In **my** chess engine, I just change the Ducks side to be whoevers turn it was. This way it can be seen as a moveable piece AND it is uncaptureable.

The obvious problem is how to do double movement. This one really stumps me, I dont use a complex move generator, so in my alpha-beta search I just ran max twice, and min twice. This probably is not a very good way to go about this (hence why my engine is trash). As the duck can sometimes be used to make a seemingly terrible move excellent, the two are connected.

#343 references a different move order, which @ianfab calls a 'workaround', and 'purely experimental' (#529), I only want an analysis engine that can ONLY process double moves, so just being a 'workaround' is fine.

In issue #343, a final closing commit is made, which I think is what finalizes the issue, creating an inefficient workaround. I would appreciate some help on implementing this to create a build version to analyze duckchess positions.

In my app, I also support a variant I created called 'DuckDuckGoose' where in addition to there being a duck on the board, there is a  goose, which after each players turn will chase the duck across the board and attempt to eat the pieces. You cannot move the duck next to the goose to prevent it ever being captured. This was really just a fun idea I had, which has no real purpose, as the game is always a draw, as any offensive measures allow for easy counterplay with usage of the goose.

In my engine, I didn't even know where to start with the goose moves,  but if it is a REALLY simple implementation, it would be fun to have it in the app.

**Comment by CrazDuck** [comment]
Sorry for the lack of a label, I cant seem to add one, it should be "Enhancement"

**Comment by jennnybuckley** [comment]
I don't exactly understand why it has to use a different turn order. If I was trying to implement this I would probably have every (piece move, duck move) pair considered as a possible move. it sounds like a lot of branching but most of them would lead to the same board position down the line so could probably be caught by memoization. I would guess that it would only run a constant factor of about 64 times slower than for normal chess.

I also have no idea what I'm talking about :)

**Comment by CrazDuck** [comment]
Doing pairs sounds like a cool idea, but, as you said, there is the matter of the branching factor. Wouldn't the engine still run fast though? Considering that crazyhouse can reach high depths quickly, and it would have a MUCH higher branching factor.

Also, even if it did run slow, it'll still be better than my alternative engine. 

How would I go about changing the move generation for every move to have both duck and normal moves? Also, wouldn't that really be screwy with undoing moves?

**Comment by ianfab** [comment]
As I mentioned in a similar discussion on discord likely the best way to implement it is using a mechanism similar to "arrow gating" as used for game of the amazons, see https://github.com/ianfab/Fairy-Stockfish/blob/596677af9a74d40773b93303fd4277d92899038f/src/movegen.cpp#L31-L42
Decisions regarding move encoding etc. should mostly follow from there. Since duck chess support either way would only be an experimental implementation and nothing that could realistically be merged to master, an upfront discussion of details seems unnecessary to me, since workarounds can simply be decided ad hoc during implementation by whoever is doing it. E.g., how to represent the duck is a relevant question, but either solution will work, whether storing it as a piece switching colors or as a moving blocking square, so one can just pick whatever suits best.

**Comment by ianfab** [comment]
Since I haven't seen anyone else picking it up and I was curious about the variant myself I did started it myself, so a first version of a duck chess implementation is available at https://github.com/ianfab/Fairy-Stockfish/tree/duck now. I consider this issue of an experimental implementation now closed. The more general request of having such a feature in main Fairy-SF can be discussed in #528, though at this point it is rather unlikely and much more likely to remain a separate branch.

**Comment by PeterNjeim** [comment]
Could you share how to understand the results? It's recommending me a set of two moves, e2e4,e4e6, etc. Does this mean I move my pawn to e4, then I move the duck to e6? How can I get this working with FairyFishGUI? I tried adding `duck:chess` to the variant list and it does show the same results as the command-line does, however no duck piece (`D`) is appearing, could you help? Thanks

**Comment by ianfab** [comment]
Regarding the protocol I am trying to adapt to what was discussed in https://talkchess.com/forum3/viewtopic.php?f=7&t=80829. Regarding GUI support I guess it is best to try to use Winboard for now. Or you can try to compile pyffish based on the duck branch and use that in FairyFishGUI. Probably won't work out of the box though.

**Comment by PeterNjeim** [comment]
Sorry for the trouble but I can't seem to get it working in WinBoard either. WinBoard keeps telling me that my moves are illegal according to Fairy Stockfish
