### ISSUE TITLE
Suggestion: compile into binaries with name fairystockfish

### ISSUE THREAD

**Issue by nguyenpham** [ianfab/Fairy-Stockfish#559]
At the moment when I compile the code it creates a new binary named stockfish. It is better to name it as fairystockfish (or any name of your choice but stockfish). That is more convenience for users and remove some confuses

**Comment by ianfab** [comment]
Since the default binary name is referenced in some test and release scripts, some of which merged from upstream, doing a renaming would be quite inconvenient from a maintenance and development perspective.

End users never see this default name since any CI build or proper release renames the binaries anyway, so developers are the only relevant here. Is there really any source for confusion here? It is within the Fairy-SF repository and the binary prints the engine name once executed, so should be fairly clear.
