### ISSUE TITLE
The debug command is not supported

### ISSUE THREAD

**Issue by antoyo** [ianfab/Fairy-Stockfish#587]
Hi.
It seems the `debug [on|off]` command is not supported.
I'm seeing `info string` lines which should be hidden when `debug` is `off`.
Also, according to [this doc](https://wbec-ridderkerk.nl/html/UCIProtocol.html):

> This mode should be switched off by default

Thanks to add this command and making it off by default.

**Comment by ianfab** [comment]
Adding a debug mode is something that can be considered, though it is not entirely clear to me which debug information should be presented there.

Regarding the `info string` lines, I do not think that
> In debug mode the engine should sent additional infos to the GUI, e.g. with the "info string" command

implies that `info string` may only be sent when debug is enabled. Since official stockfish also uses `info string` and does not support debug mode either, I assume their interpretation is the same.

**Comment by antoyo** [comment]
Oh, if Stockfish doesn't support it as well, I guess we can close this issue.
