### ISSUE TITLE
Missed mate threat in standard chess

### ISSUE THREAD

**Issue by ianfab** [ianfab/Fairy-Stockfish#68]
See move 13 in https://pychess-variants.herokuapp.com/WCxatxrK.

Originally reported in https://github.com/ianfab/Fairy-Stockfish/pull/67#issue-366779699.

**Comment by ianfab** [comment]
@thaichessswinboard Did you use the help of an engine to play this game? The position that arose at move 13 is almost study-like.

At first sight it looks like the checkmate threat was just too deep to be detected at 1sec/move, but I will check further.

**Comment by ianfab** [comment]
I started to analyze the position, it is really interesting: https://lichess.org/study/DfykOJ9R

**Comment by ianfab** [comment]
While Qe7 was a weird move I can not reproduce, the deep mate threats in this position are even overlooked by official stockfish (given 1 sec/move it plays Re8), so this is not a bug.

**Comment by thaichessswinboard** [comment]
anyway I don't know I beat program again I think is internal Bugs somewhere but less than before see my game many Thank.

[Event "PyChess casual game"]
[Site "https://pychess-variants.herokuapp.com/9Ol08MzC"]
[Date "2020.01.24"]
[Round "-"]
[White "AnonymousXIVZ"]
[Black "Fairy-Stockfish"]
[Result "1-0"]
[WhiteElo "1500"]
[BlackElo "1500"]
[TimeControl "600+1"]

1. e4 c5 2. Nf3 Nc6 3. Nc3 e6 4. h3 a6 5. Bxa6 Rxa6 6. d3 d6 7. Bd2 Nf6 8.
Qc1 Be7 9. Ne2 O-O 10. Bh6 gxh6 11. Qxh6 Nb4 12. O-O Nxc2 13. Ng5 Nxa1 14.
Ng3 Re8 15. Nh5 Nxh5 16. Qxh7+ Kf8 17. Qxf7#
1-0

**Comment by ianfab** [comment]
You try the same trick in [133 games against Fairy-Stockfish](https://pychess-variants.herokuapp.com/@/AnonymousXIVZ) and are successful once, and then you call it a bug. What is the point of this? This is just a waste of time and resources.

**Comment by thaichessswinboard** [comment]
yes mode test Bug it must like that I think it internal Bug because program doesn't know exactly checkmate it lost it must protect King more than do other thing maybe something wrong inside program. But I can Internal Bug let see my game again maybe you understand more

[Event "PyChess casual game"]
[Site "https://pychess-variants.herokuapp.com/06jkZJWe"]
[Date "2020.01.24"]
[Round "-"]
[White "AnonymousXIVZ"]
[Black "Fairy-Stockfish"]
[Result "1-0"]
[TimeControl "600+1"]
[WhiteElo "1500?"]
[BlackElo "1500?"]
[Variant "Chess"]

1. e4 d5 2. Nc3 d4 3. Nce2 e5 4. d3 c5 5. Bd2 Nf6 6. h3 Nc6 7. Nf3 Be6 8. Qc1 Be7 9. Ng3 h6 10. Be2 O-O 11. Rb1 Bxa2 12. Bxh6 gxh6 13. Qxh6 Bxb1 14. Ng5 Qa5+ 15. c3 dxc3 16. O-O Nd4 17. Nh5 Nxe2+ 18. Kh1 Ng3+ 19. fxg3 c2 20. Qg7# 1-0

**Comment by gbtami** [comment]
@thaichessswinboard please stop using pychess site for this meaningless "bug" hunting!
If you want to find bugs in any chess engine use your local computer with some desktop GUI. I suggest to try cutechess or winboard. See https://github.com/ianfab/Fairy-Stockfish/wiki/Usage
