### ISSUE TITLE
Tendency to pick risky moves for ending the game

### ISSUE THREAD

**Issue by notruck** [ianfab/Fairy-Stockfish#69]
During one of his test games, CouchTomato87 noticed FairySF making a seemingly dangerous move in an otherwise drawn game for no apparent reason.  Black has two Xiangqi Soldiers and a Rook vs White's Queen.  

![analysis-mode](https://user-images.githubusercontent.com/56622488/73115156-6022b700-3ed7-11ea-8ceb-d7d4e3de95ae.png)

It turns out that the "halfmove clock" value was already at 100, allowing for a draw claim under the 50-move rule. 

I have also seen the official Stockfish do something similar on FICS a few years ago, although I don't know if that's still the case with the latest dev version. In a KR vs KR endgame, one side put its Rook totally en prise. But the game immediately ended as a draw.  

![fairysf](https://user-images.githubusercontent.com/56622488/73115181-86485700-3ed7-11ea-88a1-4bce57b0261b.png)

FEN for the above position, analyzed with FairySF 170120: 4kr2/8/8/8/8/8/8/3RK3 b - - 100 1

In the current FIDE Laws of Chess, they require "a correct claim" for such a game to end in a draw. (Articles 5.2 e. and 9.3, copied below)

I'm wondering, does the engine make such a claim on its own, or is it up to the GUI and/or human? I just thought, unless the "risky" move is accompanied by an automatic draw-claim, it could potentially be dangerous. The engine could have just played some other safe move and held onto the draw that way. 
 
 **Article 5.2** 
      e. The  game  may  be  drawn  if  each  player  has  made  at  least  the  last  50  consecutive  moves  without  the  movement  of  any  pawn  and  without  any capture.  (See  Article  9.3)

**Article 9.3** 
          The game is drawn, upon a correct claim by the player having the move, if: 

      a. he  writes  his  move  on  his  scoresheet  and  declares  to  the  arbiter  his  intention  to make this move, which shall result in thelast50 moves having been made by each player without the movement of any pawn and without any capture, or

      b. the  last  50  consecutive  moves  have  been  made  by  each  player without   the   movement of any pawn and without any capture.

**Comment by ianfab** [comment]
The UCI protocol does not support draw claims, so the adjudication is always done by the GUI. In the xboard protocol there is some kind of draw claim (which is not implemented in SF yet), but it probably only works if the GUI anyway uses the same settings for 50 move rule. For the engine, any move that does not reset the half-move clock is equally good, since all positions are evaluated as a draw. When all moves are equally good, the move ordering is more or less random, but since checks are often searched first, they might end up as the "best" move in such a situation.

As you already noticed this behavior is inherited from official stockfish. I can have a quick look whether there is a simple solution, but most likely I can not do much about this.

**Comment by ianfab** [comment]
I checked that implementing draw claims in xboard would not change anything. It is still essential that the adjudication settings in the GUI are correct.
