### ISSUE TITLE
Atomic / Atomic-960

### ISSUE THREAD

**Issue by smartchessguiapp** [ianfab/Fairy-Stockfish#81]
Dear ianfab !

I admire your work about which I learned at https://www.pychess.org. As I was told by gbtami, adding variant Atomic to that wonderful new site requires cooperation by your engine. In Atomic white enjoys a big opening advantage ( some argue, a winning advantage ), therefore there is a great demand for Atomic-960. Many players would join if Atomic / Atomic-960 could be played at that site. Please add variant Atomic to your engine.

**Comment by ianfab** [comment]
Thanks for your feedback.

960 support more or less comes out of the box, so that would not be an issue, however, atomic in general does not fit very well into the design of this fork, which is why I ignored it so far (also see the bottom of https://github.com/ianfab/Fairy-Stockfish/issues/1#issue-335107310 for limitations considered to be difficult to resolve). Atomic still might be feasible, but some problems need to be solved:
* Touching kings are immune from check
  * [ ] legal move validation
  * [ ] evasion and non-evasion move generation
  * [ ] computation of checking pieces/moves
* Doing and undoing of atomic captures
  * [ ] Store captured pieces in state info
  * [ ] How to deal with captured promoted pieces (e.g. for atomic-zh)? Also maintain unpromoted state of captured pieces?
  * [ ] discovered checks (and illegal capture of king blockers) by atomic captures

**Comment by smartchessguiapp** [comment]
If nothing else there is always this open source fork:

https://github.com/ddugovic/Stockfish

Atomic in the above fork became quite reliable over time. I don't know if the code can be injected as is, but at least the ideas used in it can be studied.

I only understand ( somewhat ) GUI programming, so I cannot give any practical advice better than this general one.

**Comment by ianfab** [comment]
As a co-author I know that fork quite well, and my work on it actually was the main motivation to start this fork, since its design and goals impose some limitations that can not be overcome without starting a new fork from scratch. However, the huge amount of variants in this fork make it necessary to implement variants/rules with as few and simple code as possible, otherwise the whole project gets unmaintainable. Therefore, and due to allowing almost arbitrary combination of supported rules, a very different way of implementing the atomic rules is required here.

**Comment by smartchessguiapp** [comment]
May be it is easier then to somehow allow more than one engine in the pychess project than to modify this engine. This was my suggestion in the first place towards gbtami, but he redirected me here, to see if I can succeed with an issue.

I'm sorry that I'm not prepared enough in engine programming and I did not know about you being part of the ddugovic fork, I was only aware of the link.

**Comment by ianfab** [comment]
Since the engine is not only used for game play and analysis but via a python wrapper also to define the rules of the game, adding more engines adds some overhead for maintenance which is why gbtami understandably prefers to use a single engine if possible. I think sooner or later this fork might also support atomic, but I can not make any promise on that.

No problem, the discussion does not need to get too technical, I hope my high-level description of the problem is sufficient to get an idea.
