### ISSUE TITLE
s-chess UCI print where pieces are gated when castling

### ISSUE THREAD

**Issue by catask** [ianfab/Fairy-Stockfish#95]
When using fairy-stockfish in UCI, moves are recorded as e1g1e, but it's unclear whether the elephant is gated on e1 or h1. It would be nice to specify where this elephant is. Often the gated piece moves later anyway, so one can find where it is originally.

**Comment by gbtami** [comment]
h1e1e used when elephant gated to h1.

**Comment by ianfab** [comment]
As gbtami mentioned there is a disambiguation between castling on king or rook square via the origin square of the castling move. However, the UCI protocol is not really designed for manual CLI usage, so I would recommend to use a GUI, e.g., Winboard/XBoard or cutechess, depending on whether you want to use it for analysis or game play.

In any case, I do not have the freedom to change it, since the protocol has to be stable or otherwise it would break compatibility with GUIs, so I can not do anything about it. However, if you have more questions how to use it, feel free to ask.
